# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nrt

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://nrtacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e79067fc538244ed9f846b2d1edec0a9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ddb7aa817b674341804c3b4c15379fb4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nrtacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e79067fc538244ed9f846b2d1edec0a9 }}/nrt98ad:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nrt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_793276b4041d44cbbd9e668260e87836 }}
        images: 'nrtacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e79067fc538244ed9f846b2d1edec0a9 }}/nrt98ad:${{ github.sha }}'